/*
 * new64 -- fixed-point angle math and the scalar helpers the movement code is
 * built out of.
 *
 * Fidelity notes (these are the reasons this file exists at all):
 *
 *   * sins()/coss() are *table* lookups, not calls to libm.  The N64 games
 *     index a 4096-entry sine table with the top 12 bits of an s16 angle, so
 *     every angle in the low 4 bits of the s16 resolves to the same sine.
 *     Movement code that accumulates tiny yaw deltas therefore quantises in a
 *     specific, reproducible way, and anything that calls sinf() instead will
 *     drift away from the original over a long run.
 *
 *   * atan2s() takes its arguments (z, x) -- *not* (y, x) -- and returns an
 *     s16 yaw where 0 points down +Z and 0x4000 points down +X.  This matches
 *     the convention the movement code assumes everywhere.
 *
 *   * approach_s32()/approach_f32() have asymmetric increase/decrease rates
 *     and are the only way the movement code ever eases a value toward a
 *     target, so their exact clamping behaviour is load-bearing.
 */
#ifndef M64_MATH_H
#define M64_MATH_H

#include "m64_types.h"

#define M64_SINE_TABLE_LEN 4096

/* Generated by tools/gen_sintable.c; see engine/src/m64_sintable.c. */
extern const f32 gM64SineTable[M64_SINE_TABLE_LEN];

/*
 * Angle -> unit circle.  The cast to u16 before shifting is what makes
 * negative angles wrap correctly instead of sign-extending.
 */
static inline f32 m64_sins(s16 angle) {
    return gM64SineTable[(u16) angle >> 4];
}

static inline f32 m64_coss(s16 angle) {
    /* cos(a) == sin(a + 90deg) */
    return gM64SineTable[(u16) (angle + 0x4000) >> 4];
}

/* Yaw of the vector (x, z), measured from +Z toward +X, as an s16 angle. */
s16 m64_atan2s(f32 z, f32 x);

/* Full-precision variant, for callers that want radians out of the same rule. */
f32 m64_atan2f(f32 z, f32 x);

/*
 * Move `current` toward `target`, by at most `inc` when climbing and at most
 * `dec` when falling.  Never overshoots.
 */
s32 m64_approach_s32(s32 current, s32 target, s32 inc, s32 dec);
f32 m64_approach_f32(f32 current, f32 target, f32 inc, f32 dec);

/* Vector helpers.  Kept trivial and header-visible; these are hot. */
static inline void m64_vec3f_copy(Vec3f dst, const Vec3f src) {
    dst[0] = src[0];
    dst[1] = src[1];
    dst[2] = src[2];
}

static inline void m64_vec3f_set(Vec3f dst, f32 x, f32 y, f32 z) {
    dst[0] = x;
    dst[1] = y;
    dst[2] = z;
}

static inline void m64_vec3f_add(Vec3f dst, const Vec3f a) {
    dst[0] += a[0];
    dst[1] += a[1];
    dst[2] += a[2];
}

static inline void m64_vec3s_set(Vec3s dst, s16 x, s16 y, s16 z) {
    dst[0] = x;
    dst[1] = y;
    dst[2] = z;
}

f32 m64_vec3f_length(const Vec3f v);
void m64_vec3f_normalize(Vec3f v);
void m64_vec3f_cross(Vec3f dst, const Vec3f a, const Vec3f b);
f32 m64_vec3f_dot(const Vec3f a, const Vec3f b);

/* 4x4 matrix helpers used by the renderer and the camera. */
void m64_mtxf_identity(Mat4 dst);
void m64_mtxf_mul(Mat4 dst, const Mat4 a, const Mat4 b);
void m64_mtxf_perspective(Mat4 dst, f32 fovDeg, f32 aspect, f32 near, f32 far);
void m64_mtxf_look_at(Mat4 dst, const Vec3f eye, const Vec3f target, f32 roll);
void m64_mtxf_rotate_translate(Mat4 dst, const Vec3f pos, const Vec3s rotAngles, f32 scale);
void m64_mtxf_transform_point(Vec4f dst, const Mat4 m, const Vec3f p);

/* Small scalar utilities that read better than open-coded ternaries. */
static inline f32 m64_minf(f32 a, f32 b) { return a < b ? a : b; }
static inline f32 m64_maxf(f32 a, f32 b) { return a > b ? a : b; }
static inline f32 m64_clampf(f32 v, f32 lo, f32 hi) {
    return v < lo ? lo : (v > hi ? hi : v);
}
static inline s32 m64_mini(s32 a, s32 b) { return a < b ? a : b; }
static inline s32 m64_maxi(s32 a, s32 b) { return a > b ? a : b; }
static inline f32 m64_absf(f32 v) { return v < 0.0f ? -v : v; }

#endif /* M64_MATH_H */
