/*
 * new64 -- action identifiers, input bits and player flags.
 *
 * This header is the *vocabulary* half of the hosting contract.  Movement code
 * written against the N64 titles refers to states as ACT_*, to controller
 * edges as INPUT_*, and to persistent player state as MARIO_*; those names have
 * to exist, with the right semantics, before such code will compile or behave.
 *
 * How the action constants are built
 * ----------------------------------
 * An action is a single u32 packing three things:
 *
 *   bits 0-8   a per-group ordinal identifying the action
 *   bits 6-8   (overlapping) the action *group*, which selects which
 *              mario_execute_*_action() handles it
 *   bits 9+    behavioural flags queried by generic code
 *
 * The flags are the load-bearing part.  Generic engine code never asks "is this
 * ACT_TRIPLE_JUMP"; it asks "does this action have ACT_FLAG_AIR" or
 * "...ACT_FLAG_ATTACKING".  Getting a flag wrong on one action therefore
 * misbehaves everywhere, whereas the ordinals below are engine-internal: they
 * only ever have to agree with themselves, because hosted code refers to
 * actions through these same macros.
 */
#ifndef NEW64_SM64_H
#define NEW64_SM64_H

#include <PR/ultratypes.h>

/* --- Action decomposition ----------------------------------------------- */

#define ACT_ID_MASK    0x0000003F
#define ACT_GROUP_MASK 0x000001C0

#define ACT_GROUP_STATIONARY (0 << 6)
#define ACT_GROUP_MOVING     (1 << 6)
#define ACT_GROUP_AIRBORNE   (2 << 6)
#define ACT_GROUP_SUBMERGED  (3 << 6)
#define ACT_GROUP_CUTSCENE   (4 << 6)
#define ACT_GROUP_AUTOMATIC  (5 << 6)
#define ACT_GROUP_OBJECT     (6 << 6)

/* --- Action flags ------------------------------------------------------- */

#define ACT_FLAG_STATIONARY               (1 <<  9)
#define ACT_FLAG_MOVING                   (1 << 10)
#define ACT_FLAG_AIR                      (1 << 11)
#define ACT_FLAG_INTANGIBLE               (1 << 12)
#define ACT_FLAG_SWIMMING                 (1 << 13)
#define ACT_FLAG_METAL_WATER              (1 << 14)
#define ACT_FLAG_SHORT_HITBOX             (1 << 15)
#define ACT_FLAG_RIDING_SHELL             (1 << 16)
#define ACT_FLAG_INVULNERABLE             (1 << 17)
#define ACT_FLAG_BUTT_OR_STOMACH_SLIDE    (1 << 18)
#define ACT_FLAG_DIVING                   (1 << 19)
#define ACT_FLAG_ON_POLE                  (1 << 20)
#define ACT_FLAG_HANGING                  (1 << 21)
#define ACT_FLAG_IDLE                     (1 << 22)
#define ACT_FLAG_ATTACKING                (1 << 23)
#define ACT_FLAG_ALLOW_VERTICAL_WIND_ACTION (1 << 24)
/* Releasing the jump button mid-ascent only cuts the jump short for actions
 * carrying this flag. Backflips and long jumps deliberately lack it. */
#define ACT_FLAG_CONTROL_JUMP_HEIGHT      (1 << 25)
#define ACT_FLAG_ALLOW_FIRST_PERSON       (1 << 26)
#define ACT_FLAG_PAUSE_EXIT               (1 << 27)
#define ACT_FLAG_SWIMMING_OR_FLYING       (1 << 28)
#define ACT_FLAG_WATER_OR_TEXT            (1 << 29)
#define ACT_FLAG_THROWING                 (1u << 31)

/* --- Stationary actions ------------------------------------------------- */

#define ACT_IDLE            (0x001 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_IDLE | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_START_SLEEPING  (0x002 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_IDLE | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_SLEEPING        (0x003 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_IDLE | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_WAKING_UP       (0x004 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_PANTING         (0x005 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_IDLE | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_STANDING_AGAINST_WALL (0x009 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_COUGHING        (0x00A | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_IDLE | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_SHIVERING       (0x00B | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_IDLE | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_BRAKING_STOP    (0x00D | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_CROUCHING       (0x00E | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_SHORT_HITBOX | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_START_CROUCHING (0x00F | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_SHORT_HITBOX | ACT_FLAG_PAUSE_EXIT)
#define ACT_STOP_CROUCHING  (0x010 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_SHORT_HITBOX | ACT_FLAG_PAUSE_EXIT)
#define ACT_START_CRAWLING  (0x011 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_SHORT_HITBOX | ACT_FLAG_PAUSE_EXIT)
#define ACT_STOP_CRAWLING   (0x012 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_SHORT_HITBOX | ACT_FLAG_PAUSE_EXIT)
#define ACT_SLIDE_KICK_SLIDE_STOP (0x013 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_ATTACKING)
#define ACT_FIRST_PERSON    (0x016 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY)
#define ACT_BACKFLIP_LAND_STOP    (0x017 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_JUMP_LAND_STOP        (0x018 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_DOUBLE_JUMP_LAND_STOP (0x019 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_FREEFALL_LAND_STOP    (0x01A | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_SIDE_FLIP_LAND_STOP   (0x01B | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_TWIRL_LAND      (0x021 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_ATTACKING)
#define ACT_TRIPLE_JUMP_LAND_STOP (0x022 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_ALLOW_FIRST_PERSON)
#define ACT_GROUND_POUND_LAND     (0x023 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_ATTACKING)
#define ACT_LONG_JUMP_LAND_STOP   (0x024 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_BUTT_SLIDE_STOP       (0x025 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_HOLD_IDLE             (0x007 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_IDLE)
#define ACT_HOLD_HEAVY_IDLE       (0x008 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_IDLE)
#define ACT_IN_QUICKSAND          (0x00C | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY)
#define ACT_HOLD_JUMP_LAND_STOP   (0x01C | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY)
#define ACT_HOLD_FREEFALL_LAND_STOP (0x01D | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY)
#define ACT_AIR_THROW_LAND        (0x01E | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_THROWING)
#define ACT_LAVA_BOOST_LAND       (0x020 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_INVULNERABLE)
#define ACT_SHOCKWAVE_BOUNCE      (0x014 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_INVULNERABLE)
#define ACT_STOMACH_SLIDE_STOP    (0x026 | ACT_GROUP_STATIONARY | ACT_FLAG_STATIONARY | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)

/* The zero action: "no action set". Used as a sentinel in landing tables to
 * mean "fall back to the default jump" rather than as a real state. */
#define ACT_UNINITIALIZED   0x00000000

/* --- Moving (ground) actions -------------------------------------------- */

#define ACT_WALKING         (0x000 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_ALLOW_FIRST_PERSON)
#define ACT_HOLD_WALKING    (0x002 | ACT_GROUP_MOVING | ACT_FLAG_MOVING)
#define ACT_TURNING_AROUND  (0x003 | ACT_GROUP_MOVING | ACT_FLAG_MOVING)
#define ACT_FINISH_TURNING_AROUND (0x004 | ACT_GROUP_MOVING | ACT_FLAG_MOVING)
#define ACT_BRAKING         (0x005 | ACT_GROUP_MOVING | ACT_FLAG_MOVING)
#define ACT_CRAWLING        (0x008 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_SHORT_HITBOX)
#define ACT_DECELERATING    (0x00A | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_ALLOW_FIRST_PERSON)
#define ACT_HOLD_DECELERATING (0x00B | ACT_GROUP_MOVING | ACT_FLAG_MOVING)
#define ACT_BUTT_SLIDE      (0x00C | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_BUTT_OR_STOMACH_SLIDE | ACT_FLAG_ATTACKING)
#define ACT_STOMACH_SLIDE   (0x00D | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_BUTT_OR_STOMACH_SLIDE | ACT_FLAG_DIVING | ACT_FLAG_ATTACKING)
#define ACT_HOLD_BUTT_SLIDE (0x00E | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_BUTT_OR_STOMACH_SLIDE)
#define ACT_DIVE_SLIDE      (0x010 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_DIVING | ACT_FLAG_ATTACKING)
#define ACT_MOVE_PUNCHING   (0x011 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_ATTACKING)
#define ACT_CROUCH_SLIDE    (0x013 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_SHORT_HITBOX | ACT_FLAG_ATTACKING)
#define ACT_SLIDE_KICK_SLIDE (0x014 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_ATTACKING)
#define ACT_JUMP_LAND       (0x018 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_ALLOW_FIRST_PERSON)
#define ACT_FREEFALL_LAND   (0x019 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_ALLOW_FIRST_PERSON)
#define ACT_DOUBLE_JUMP_LAND (0x01A | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_ALLOW_FIRST_PERSON)
#define ACT_SIDE_FLIP_LAND  (0x01B | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_ALLOW_FIRST_PERSON)
#define ACT_HOLD_JUMP_LAND  (0x01C | ACT_GROUP_MOVING | ACT_FLAG_MOVING)
#define ACT_HOLD_FREEFALL_LAND (0x01D | ACT_GROUP_MOVING | ACT_FLAG_MOVING)
#define ACT_TRIPLE_JUMP_LAND (0x01F | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_ALLOW_FIRST_PERSON)
#define ACT_BACKFLIP_LAND   (0x020 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_ALLOW_FIRST_PERSON)
#define ACT_LONG_JUMP_LAND  (0x01E | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_ALLOW_FIRST_PERSON)
/* A request to start sliding that resolves to butt- or stomach-slide depending
 * on which way you face relative to the slope. Never a state you stay in. */
#define ACT_BEGIN_SLIDING   (0x009 | ACT_GROUP_MOVING | ACT_FLAG_MOVING)
#define ACT_HOLD_BEGIN_SLIDING (0x00F | ACT_GROUP_MOVING | ACT_FLAG_MOVING)
#define ACT_HOLD_STOMACH_SLIDE (0x012 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_BUTT_OR_STOMACH_SLIDE | ACT_FLAG_DIVING)
#define ACT_QUICKSAND_JUMP_LAND (0x015 | ACT_GROUP_MOVING | ACT_FLAG_MOVING)
#define ACT_HOLD_QUICKSAND_JUMP_LAND (0x016 | ACT_GROUP_MOVING | ACT_FLAG_MOVING)
#define ACT_GROUND_BONK     (0x017 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_INVULNERABLE)
#define ACT_SOFT_BACKWARD_GROUND_KB (0x021 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_INVULNERABLE)
#define ACT_SOFT_FORWARD_GROUND_KB  (0x022 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_INVULNERABLE)
#define ACT_BACKWARD_GROUND_KB      (0x023 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_INVULNERABLE)
#define ACT_FORWARD_GROUND_KB       (0x024 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_INVULNERABLE)
#define ACT_HARD_BACKWARD_GROUND_KB (0x025 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_INVULNERABLE)
#define ACT_HARD_FORWARD_GROUND_KB  (0x026 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_INVULNERABLE)
#define ACT_BURNING_GROUND          (0x027 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_INVULNERABLE)
#define ACT_RIDING_SHELL_GROUND     (0x028 | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_RIDING_SHELL)
#define ACT_HOLD_HEAVY_WALKING      (0x029 | ACT_GROUP_MOVING | ACT_FLAG_MOVING)
/* Standing punch/kick combo. Shares its implementation with ACT_MOVE_PUNCHING,
 * differing only in the speed it starts from. */
#define ACT_PUNCHING                (0x02A | ACT_GROUP_MOVING | ACT_FLAG_MOVING | ACT_FLAG_ATTACKING)

/* --- Airborne actions --------------------------------------------------- */

#define ACT_JUMP            (0x000 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_ALLOW_VERTICAL_WIND_ACTION | ACT_FLAG_CONTROL_JUMP_HEIGHT)
#define ACT_DOUBLE_JUMP     (0x001 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_ALLOW_VERTICAL_WIND_ACTION | ACT_FLAG_CONTROL_JUMP_HEIGHT)
#define ACT_TRIPLE_JUMP     (0x002 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_ATTACKING)
#define ACT_BACKFLIP        (0x003 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR)
#define ACT_STEEP_JUMP      (0x004 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_CONTROL_JUMP_HEIGHT)
#define ACT_WALL_KICK_AIR   (0x005 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_CONTROL_JUMP_HEIGHT)
#define ACT_SIDE_FLIP       (0x006 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_CONTROL_JUMP_HEIGHT)
#define ACT_LONG_JUMP       (0x007 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_ATTACKING)
#define ACT_WATER_JUMP      (0x008 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_CONTROL_JUMP_HEIGHT)
#define ACT_DIVE            (0x009 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_DIVING | ACT_FLAG_ATTACKING)
#define ACT_FREEFALL        (0x00B | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR)
#define ACT_BUTT_SLIDE_AIR  (0x00D | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_BUTT_OR_STOMACH_SLIDE)
#define ACT_FLYING_TRIPLE_JUMP (0x00F | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_CONTROL_JUMP_HEIGHT)
#define ACT_SHOT_FROM_CANNON (0x010 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_DIVING | ACT_FLAG_ATTACKING)
#define ACT_FLYING          (0x011 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_ATTACKING)
#define ACT_VERTICAL_WIND   (0x014 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_DIVING)
#define ACT_HOLD_JUMP       (0x015 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_CONTROL_JUMP_HEIGHT)
#define ACT_HOLD_FREEFALL   (0x016 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR)
#define ACT_HOLD_BUTT_SLIDE_AIR (0x017 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_BUTT_OR_STOMACH_SLIDE)
#define ACT_TWIRLING        (0x019 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_ATTACKING)
#define ACT_FORWARD_ROLLOUT (0x01A | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_ATTACKING)
#define ACT_AIR_HIT_WALL    (0x01B | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR)
#define ACT_GROUND_POUND    (0x01C | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_ATTACKING | ACT_FLAG_INVULNERABLE)
#define ACT_SLIDE_KICK      (0x01D | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_ATTACKING)
#define ACT_JUMP_KICK       (0x01F | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_ATTACKING)
#define ACT_BACKWARD_ROLLOUT (0x020 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_ATTACKING)
#define ACT_SPECIAL_TRIPLE_JUMP (0x022 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_ATTACKING)
#define ACT_BACKWARD_AIR_KB (0x023 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_INVULNERABLE)
#define ACT_FORWARD_AIR_KB  (0x024 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_INVULNERABLE)
#define ACT_HARD_FORWARD_AIR_KB (0x025 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_INVULNERABLE)
#define ACT_HARD_BACKWARD_AIR_KB (0x026 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_INVULNERABLE)
#define ACT_BURNING_JUMP    (0x027 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_INVULNERABLE)
#define ACT_BURNING_FALL    (0x028 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_INVULNERABLE)
#define ACT_LAVA_BOOST      (0x02A | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_INVULNERABLE)
#define ACT_GETTING_BLOWN   (0x02B | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_INVULNERABLE)
#define ACT_THROWN_FORWARD  (0x02D | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_INVULNERABLE)
#define ACT_THROWN_BACKWARD (0x02E | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_INVULNERABLE)
#define ACT_FALL_AFTER_STAR_GRAB (0x02F | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR)
#define ACT_AIR_THROW            (0x030 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_THROWING)
#define ACT_HOLD_WATER_JUMP      (0x031 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_CONTROL_JUMP_HEIGHT)
#define ACT_TOP_OF_POLE_JUMP     (0x032 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_CONTROL_JUMP_HEIGHT)
#define ACT_DIVE_PICKING_UP      (0x033 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR)
#define ACT_RIDING_SHELL_JUMP    (0x034 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_RIDING_SHELL | ACT_FLAG_CONTROL_JUMP_HEIGHT)
#define ACT_RIDING_SHELL_FALL    (0x035 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR | ACT_FLAG_RIDING_SHELL)
#define ACT_CRAZY_BOX_BOUNCE     (0x036 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR)
/* A weak bonk off a wall: you drop, but keep control. The strong version is
 * ACT_BACKWARD_AIR_KB, chosen above 38 units/frame. */
#define ACT_SOFT_BONK            (0x037 | ACT_GROUP_AIRBORNE | ACT_FLAG_AIR)

/* --- Submerged actions -------------------------------------------------- */
/*
 * The demo level has no water, so these states are reachable only if a level
 * defines a water plane.  They are declared in full because hosted submerged
 * sources reference them, and because set_water_plunge_action() -- which *is*
 * called from ordinary landing code -- names ACT_WATER_PLUNGE.
 */
#define ACT_WATER_IDLE          (0x000 | ACT_GROUP_SUBMERGED | ACT_FLAG_STATIONARY | ACT_FLAG_SWIMMING | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_HOLD_WATER_IDLE     (0x001 | ACT_GROUP_SUBMERGED | ACT_FLAG_STATIONARY | ACT_FLAG_SWIMMING | ACT_FLAG_PAUSE_EXIT | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_WATER_ACTION_END    (0x002 | ACT_GROUP_SUBMERGED | ACT_FLAG_STATIONARY | ACT_FLAG_SWIMMING | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_HOLD_WATER_ACTION_END (0x003 | ACT_GROUP_SUBMERGED | ACT_FLAG_STATIONARY | ACT_FLAG_SWIMMING | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_DROWNING            (0x004 | ACT_GROUP_SUBMERGED | ACT_FLAG_STATIONARY | ACT_FLAG_SWIMMING | ACT_FLAG_INTANGIBLE | ACT_FLAG_INVULNERABLE | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_BACKWARD_WATER_KB   (0x005 | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_SWIMMING | ACT_FLAG_INVULNERABLE | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_FORWARD_WATER_KB    (0x006 | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_SWIMMING | ACT_FLAG_INVULNERABLE | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_WATER_DEATH         (0x007 | ACT_GROUP_SUBMERGED | ACT_FLAG_STATIONARY | ACT_FLAG_SWIMMING | ACT_FLAG_INTANGIBLE | ACT_FLAG_INVULNERABLE | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_WATER_SHOCKED       (0x008 | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_SWIMMING | ACT_FLAG_INVULNERABLE | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_BREASTSTROKE        (0x009 | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_SWIMMING | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_SWIMMING_END        (0x00A | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_SWIMMING | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_FLUTTER_KICK        (0x00B | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_SWIMMING | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_HOLD_BREASTSTROKE   (0x00C | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_SWIMMING | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_HOLD_SWIMMING_END   (0x00D | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_SWIMMING | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_HOLD_FLUTTER_KICK   (0x00E | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_SWIMMING | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_WATER_SHELL_SWIMMING (0x00F | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_SWIMMING | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_WATER_THROW         (0x010 | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_SWIMMING | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_WATER_PUNCH         (0x011 | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_SWIMMING | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
/* Entered from *land* actions on touching water, so it is reachable even
 * without any swimming code present. */
#define ACT_WATER_PLUNGE        (0x012 | ACT_GROUP_SUBMERGED | ACT_FLAG_SWIMMING | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_CAUGHT_IN_WHIRLPOOL (0x013 | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_SWIMMING | ACT_FLAG_INVULNERABLE | ACT_FLAG_SWIMMING_OR_FLYING | ACT_FLAG_WATER_OR_TEXT)
#define ACT_METAL_WATER_STANDING (0x014 | ACT_GROUP_SUBMERGED | ACT_FLAG_STATIONARY | ACT_FLAG_METAL_WATER | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_HOLD_METAL_WATER_STANDING (0x015 | ACT_GROUP_SUBMERGED | ACT_FLAG_STATIONARY | ACT_FLAG_METAL_WATER | ACT_FLAG_PAUSE_EXIT)
#define ACT_METAL_WATER_WALKING (0x016 | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_METAL_WATER)
#define ACT_HOLD_METAL_WATER_WALKING (0x017 | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_METAL_WATER)
#define ACT_METAL_WATER_FALLING (0x018 | ACT_GROUP_SUBMERGED | ACT_FLAG_STATIONARY | ACT_FLAG_METAL_WATER)
#define ACT_HOLD_METAL_WATER_FALLING (0x019 | ACT_GROUP_SUBMERGED | ACT_FLAG_STATIONARY | ACT_FLAG_METAL_WATER)
#define ACT_METAL_WATER_FALL_LAND (0x01A | ACT_GROUP_SUBMERGED | ACT_FLAG_STATIONARY | ACT_FLAG_METAL_WATER)
#define ACT_HOLD_METAL_WATER_FALL_LAND (0x01B | ACT_GROUP_SUBMERGED | ACT_FLAG_STATIONARY | ACT_FLAG_METAL_WATER)
#define ACT_METAL_WATER_JUMP    (0x01C | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_METAL_WATER)
#define ACT_HOLD_METAL_WATER_JUMP (0x01D | ACT_GROUP_SUBMERGED | ACT_FLAG_MOVING | ACT_FLAG_METAL_WATER)
#define ACT_METAL_WATER_JUMP_LAND (0x01E | ACT_GROUP_SUBMERGED | ACT_FLAG_STATIONARY | ACT_FLAG_METAL_WATER)
#define ACT_HOLD_METAL_WATER_JUMP_LAND (0x01F | ACT_GROUP_SUBMERGED | ACT_FLAG_STATIONARY | ACT_FLAG_METAL_WATER)

/* --- Automatic actions -------------------------------------------------- */

#define ACT_LEDGE_GRAB      (0x000 | ACT_GROUP_AUTOMATIC | ACT_FLAG_STATIONARY | ACT_FLAG_HANGING | ACT_FLAG_PAUSE_EXIT)
#define ACT_LEDGE_CLIMB_SLOW_1 (0x001 | ACT_GROUP_AUTOMATIC | ACT_FLAG_HANGING | ACT_FLAG_INVULNERABLE)
#define ACT_LEDGE_CLIMB_SLOW_2 (0x002 | ACT_GROUP_AUTOMATIC | ACT_FLAG_HANGING | ACT_FLAG_INVULNERABLE)
#define ACT_LEDGE_CLIMB_DOWN   (0x003 | ACT_GROUP_AUTOMATIC | ACT_FLAG_HANGING | ACT_FLAG_INVULNERABLE)
#define ACT_LEDGE_CLIMB_FAST   (0x004 | ACT_GROUP_AUTOMATIC | ACT_FLAG_HANGING | ACT_FLAG_INVULNERABLE)
#define ACT_WALL_SLIDE         (0x00E | ACT_GROUP_AUTOMATIC | ACT_FLAG_AIR)
#define ACT_START_HANGING      (0x005 | ACT_GROUP_AUTOMATIC | ACT_FLAG_HANGING | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_HANGING            (0x006 | ACT_GROUP_AUTOMATIC | ACT_FLAG_STATIONARY | ACT_FLAG_HANGING | ACT_FLAG_ALLOW_FIRST_PERSON | ACT_FLAG_PAUSE_EXIT)
#define ACT_HANG_MOVING        (0x007 | ACT_GROUP_AUTOMATIC | ACT_FLAG_MOVING | ACT_FLAG_HANGING)
#define ACT_IN_CANNON          (0x00F | ACT_GROUP_AUTOMATIC | ACT_FLAG_STATIONARY | ACT_FLAG_INTANGIBLE)

/* --- Cutscene / uncontrolled -------------------------------------------- */

#define ACT_DISAPPEARED     (0x004 | ACT_GROUP_CUTSCENE | ACT_FLAG_STATIONARY | ACT_FLAG_INTANGIBLE | ACT_FLAG_INVULNERABLE)
#define ACT_SQUISHED        (0x008 | ACT_GROUP_CUTSCENE | ACT_FLAG_STATIONARY | ACT_FLAG_INVULNERABLE)
#define ACT_STANDING_DEATH  (0x009 | ACT_GROUP_CUTSCENE | ACT_FLAG_STATIONARY | ACT_FLAG_INTANGIBLE | ACT_FLAG_INVULNERABLE)

/* --- Input bits --------------------------------------------------------- */
/*
 * These are recomputed from scratch every frame in update_mario_inputs(); they
 * are a digest of the controller plus the player's immediate surroundings, not
 * raw button state.  The _PRESSED bits are edges, the _DOWN bits are levels.
 */
#define INPUT_NONZERO_ANALOG         0x0001
#define INPUT_A_PRESSED              0x0002
#define INPUT_OFF_FLOOR              0x0004
#define INPUT_ABOVE_SLIDE            0x0008
#define INPUT_FIRST_PERSON           0x0010
#define INPUT_UNKNOWN_5              0x0020
#define INPUT_SQUISHED               0x0040
#define INPUT_A_DOWN                 0x0080
#define INPUT_IN_POISON_GAS          0x0100
#define INPUT_IN_WATER               0x0200
#define INPUT_STOMPED                0x0400
#define INPUT_INTERACT_OBJ_GRABBABLE 0x0800
#define INPUT_UNKNOWN_12             0x1000
#define INPUT_B_PRESSED              0x2000
#define INPUT_Z_DOWN                 0x4000
#define INPUT_Z_PRESSED              0x8000

/* --- Controller buttons ------------------------------------------------- */

#define A_BUTTON     0x8000
#define B_BUTTON     0x4000
#define Z_TRIG       0x2000
#define START_BUTTON 0x1000
#define U_JPAD       0x0800
#define D_JPAD       0x0400
#define L_JPAD       0x0200
#define R_JPAD       0x0100
#define L_TRIG       0x0020
#define R_TRIG       0x0010
#define A_CBUTTONS   0x0008
#define B_CBUTTONS   0x0004
#define U_CBUTTONS   0x0008
#define D_CBUTTONS   0x0004
#define L_CBUTTONS   0x0002
#define R_CBUTTONS   0x0001

/* --- Persistent player flags -------------------------------------------- */
/*
 * The names here follow the hosting contract rather than description, because
 * movement code refers to them literally.  What each one actually gates is
 * noted alongside.
 */
#define MARIO_NORMAL_CAP         0x00000001
#define MARIO_VANISH_CAP         0x00000002
#define MARIO_METAL_CAP          0x00000004
#define MARIO_WING_CAP           0x00000008
#define MARIO_CAP_ON_HEAD        0x00000010
#define MARIO_CAP_IN_HAND        0x00000020
/* Composite: wearing the wing cap *and* having it on your head. Tested as an
 * equality against the mask, not a bitwise-any, since either bit alone is a
 * different state. */
#define MARIO_WING_CAP_ON_HEAD   (MARIO_WING_CAP | MARIO_CAP_ON_HEAD)
#define MARIO_METAL_CAP_ON_HEAD  (MARIO_METAL_CAP | MARIO_CAP_ON_HEAD)
#define MARIO_VANISH_CAP_ON_HEAD (MARIO_VANISH_CAP | MARIO_CAP_ON_HEAD)
#define MARIO_METAL_SHOCK        0x00000040
#define MARIO_TELEPORTING        0x00000080
/* Set while a jump is "live". Gates the release-to-shorten-jump rule, so
 * clearing it mid-ascent locks in full jump height. */
#define MARIO_UNKNOWN_08         0x00000100
#define MARIO_UNKNOWN_13         0x00002000
#define MARIO_ACTION_SOUND_PLAYED 0x00010000
#define MARIO_MARIO_SOUND_PLAYED 0x00020000
#define MARIO_UNKNOWN_18         0x00040000
#define MARIO_PUNCHING           0x00100000
#define MARIO_KICKING            0x00200000
#define MARIO_TRIPPING           0x00400000
#define MARIO_UNKNOWN_25         0x02000000
/* Set when an air step was stopped by a wall; read by wall-kick timing. */
#define MARIO_UNKNOWN_30         0x40000000
#define MARIO_UNKNOWN_31         0x80000000

/* --- Particle flags ----------------------------------------------------- */
/*
 * new64 has no particle system yet; these exist so hosted code that raises
 * them compiles and so a future renderer can consume them.
 */
#define PARTICLE_DUST                 (1 <<  0)
#define PARTICLE_VERTICAL_STAR        (1 <<  1)
#define PARTICLE_HORIZONTAL_STAR      (1 <<  3)
#define PARTICLE_SPARKLES             (1 <<  4)
#define PARTICLE_water_splash         (1 <<  5)
#define PARTICLE_SHALLOW_WATER_WAVE   (1 <<  8)
#define PARTICLE_SHALLOW_WATER_SPLASH (1 <<  9)
#define PARTICLE_LEAF                 (1 << 12)
#define PARTICLE_SNOW                 (1 << 13)
#define PARTICLE_MIST_CIRCLE          (1 << 15)
#define PARTICLE_BREATH               (1 << 17)
#define PARTICLE_TRIANGLE             (1 << 18)
#define PARTICLE_WAVE_TRAIL           (1 <<  2)
#define PARTICLE_FIRE                 (1 <<  6)
#define PARTICLE_IDLE_WATER_WAVE      (1 <<  7)
#define PARTICLE_PLUNGE_BUBBLE        (1 << 10)
#define PARTICLE_WATER_SPLASH         (1 <<  5)
#define PARTICLE_BUBBLE               (1 << 16)

/* --- Model / terrain ids used by movement code -------------------------- */

#define TERRAIN_GRASS  0x0000
#define TERRAIN_STONE  0x0001
#define TERRAIN_SNOW   0x0002
#define TERRAIN_SAND   0x0003
#define TERRAIN_SPOOKY 0x0004
#define TERRAIN_WATER  0x0005
#define TERRAIN_SLIDE  0x0006
#define TERRAIN_MASK   0x0007

/* Frame rate the movement code is written against.  Everything about the
 * physics tuning assumes this; running the state machine at any other rate
 * changes jump heights and speeds. */
#define FRAME_RATE 30

#endif /* NEW64_SM64_H */
